config/routes.rb
Mobile2youServer::Application.routes.draw do

  resources :user_applicants
  resources :status_user_jobs
  resources :mannequin_sizes
  resources :answers
  resources :phones
  resources :questions
  resources :statuses
  resources :nationalities
  resources :origin_countries
  resources :schoolings
  resources :passport_nationalities
  resources :cnhs
  resources :notifications
  resources :portfolios
  resources :addresses
  resources :pictures
  resources :user_apps
  resources :super_admins
  resources :usuarios
  resources :webs
  resources :admins
  resources :skill_contents
  resources :appearance_contents
  resources :performance_contents
  resources :performances
  resources :appearances
  resources :skills
  resources :jobs
  resources :user_producers
  resources :download

  apipie
  devise_for :users
  resources :users

  # match 'pesquisa.agenciamondiale.com.br' => redirect('https://agenciamondiale.com.br/')
  # if request.fullpath.include?("pesquisa.agenciamondiale")
  #    redirect_to "https://agenciamondiale.com.br/"
  #  end

  # get '/' => 'openJob', :constraints => { :subdomain => /.+/ }
  # constraints subdomain: 'pesquisa' do
  #   root to: 'openJob'
  # end

  # constraints subdomain: false do
    # root to: 'webs#open_job'
  # end
  constraints(Subdomain) do
    match '/' => 'webs#open_job'
  end
  root to: 'home#index'

  # get '/webs/download'=> 'webs#download'
  get 'index' => 'webs#index'
  get 'signup' => 'webs#user_signup'
  get 'anunciar' => 'webs#new_job'
  get 'gerenciar' => 'webs#manage_jobs'
  get 'openJob' => 'webs#open_job'
  get 'editOpenJob/:id' => 'webs#edit_open_job'
  get 'openJobSub' => 'webs#open_job_subscribe'
  get 'search' => 'webs#search_users'
  get 'admin' => 'home#index'
  get 'login' => 'home#index'
  get "alterar_senha" => "usuarios#edit"
  get "meu_perfil" => "usuarios#edit"
  get "publicPerfil" => "webs#public_perfil"
  get "editPublicPerfil" => "webs#edit_public_perfil"
  get 'approve/:id' => 'user_apps#approve', as: :approve
  get 'repprove/:id' => 'user_apps#repprove', as: :repprove
  get 'seen/:id' => 'user_applicants#seen', as: :seen
  post 'user_applicants/destroy_many' 
  post 'user_applicants/send_email' 
  get 'get_user_perfil'  => 'webs#get_user_perfil'


  resources :user_applicants, only: [:index, :show] do
    resource :download, only: [:show]
  end

  namespace :web do
    post "users/signin"
    post 'users/new'
    post 'jobs/new'
    post 'jobs/newOpenJob'
    post 'jobs/editOpenJob'
    post 'jobs/apply'
    post 'jobs/applyOpenJob'
    post 'jobs/editApplyOpenJob'
    get 'users/download'  
  end

  namespace :webservices do
    post "login/signin"
    post "login/signinFacebook"
    post "login/signup"
    post "login/forgotPass"
    # get 'jobs/openPesquisaJobs'


    post "account/updatePassword"
    post "account/checkPassword"
    post "account/updatePhoto"
    post "account/registerToken"
    
    # get 'account/getSubscribeInfo'
    # get "account/getAbout"
    # get "account/getNotifications"

    # put "account/updateAbout"
    # put 'account/updateLanguage'

    get "jobs/openJobs"
    get "jobs/myJobs"

    post "jobs/apply"
    post "jobs/addMediaAnswer"

    delete "jobs/removeMediaAnswer"

    get "account/about"
    get "account/myGallery"
    get "account/getCharacteristics"
    get "account/getFirstContact"
    get "account/getSkills"
    get "account/getPersonalData"
    get "account/getSocialNetworks"
    get "account/notifications"
    
    post "account/createFirstContact"
    post "account/addCurriculum"
    post "account/addGallery"
    post "account/addPicture"

    put "account/editFirstContact"
    put "account/editSkills"
    put "account/editPersonalData"
    put "account/editSocialNetworks"
    put "account/editCharacteristics"

    delete "account/removeGallery"
    delete "account/removePicture"
    delete "account/removeCurriculum"
  end

  match ':controller(/:action(/:id))(.:format)'

end

app/models/skill_content.rb
class SkillContent
  include Mongoid::Document
  field :name, type: String
  field :parent_name, type: String

  belongs_to :skill
  
  has_and_belongs_to_many :users_prof, :class_name => "UserApp", :inverse_of => :skill_contents_prof
  has_and_belongs_to_many :users_jr, :class_name => "UserApp", :inverse_of => :skill_contents_jr

  has_and_belongs_to_many :job_skill_prof, :class_name => "Job", :inverse_of => :skill_job_contents_prof
  has_and_belongs_to_many :job_skill_jr, :class_name => "Job", :inverse_of => :skill_job_contents_jr

end

app/controllers/skill_contents_controller.rb
class SkillContentsController < ApplicationController
  before_filter :set_skill_content, only: [:show, :edit, :update, :destroy]
  before_filter :checkUser

  def checkUser
    if !current_user.isSuperAdmin?
      redirect_to "/admin"
    end
  end
  
  respond_to :html

  def index
    @skill_contents = SkillContent.all
    respond_with(@skill_contents)
  end

  def show
    respond_with(@skill_content)
  end

  def new
    @skill_content = SkillContent.new
    respond_with(@skill_content)
  end

  def edit
  end

  def create
    @skill_content = SkillContent.new(params[:skill_content])
    @skill_content.parent_name = @skill_content.skill.name

    flash[:notice_success] = 'Criado com sucesso.' if @skill_content.save
    respond_with(@skill_content)
  end

  def update
    @skill_content.update_attributes(params[:skill_content])
    @skill_content.parent_name = @skill_content.skill.name
    
    flash[:notice_success] = 'Atualizado com sucesso.' if @skill_content.save
    respond_with(@skill_content)
  end

  def destroy
    @skill_content.destroy
    respond_with(@skill_content)
  end

  private
    def set_skill_content
      @skill_content = SkillContent.find(params[:id])
    end
end

app/helpers/skill_contents_helper.rb
module SkillContentsHelper
end

app/views/skill_contents/_form.html.erb
<style type="text/css">
.input-error {
  color :red;
}
</style>
<% iterator = @skill_content %>
<% @skills = Skill.all %>
<% title = "Dados do Conteúdo da Habilidade" %>

<%= form_for(iterator, :validate => true)  do |f| %>
  <div class="row">
    <div class="col-md-8">
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title"><%= title %></h3>
        </div>
        <div class="box-body">
          <!-- nome -->
          <div class="form-group">
              <label for="">Nome<span style="color:red">*</span></label>
              <%= f.text_field :name, :placeholder => "Digite o nome", :class => "form-control", :required => true %>
          </div>

          <!--Habilidades-->
          <div class="form-group">
            <label>Selecione uma Habilidade</label>
              <select class="form-control chosen-select" data-placeholder="Escolha o formulario" id="chosen_skill" name="skill_content[skill]">
                <% @skills.each do |u| %>
                  <% if iterator.skill == u %>
                      <option value="<%= u.id %>" selected><%= u.name %></option>
                  <% else %>
                      <option value="<%= u.id %>"><%= u.name %></option>
                  <% end %>
                <% end %>
              </select>
          </div>

        </div>
        <div class="box-footer">
          <%= f.submit "Salvar", :class => "btn btn-primary" %> 
          <%= link_to "Todos Conteúdos da Habilidade", skill_contents_path,:class => "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>  
<% end %>

app/views/skill_contents/edit.html.erb
<%= render 'form' %>

app/views/skill_contents/index.html.erb
<div class="row">

  <%= notice_helper %>
  <% cols = ["Nome","Habilidade", "Opções"] %>
  <% path = "skill_contents" %>
  <% new_button_title = "Novo conteúdo" %>
  <% remove_title = "Deseja remover este Conteúdo?" %>
  <% iterator = @skill_contents %>

  <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <% if Skill.all.count > 0 %>
            <a href="<%= path %>/new" class="btn btn-primary pull-right" style="color:white; margin:10px;"> <%= new_button_title %></a>
          <% else %>
            <span class="btn btn-default pull-right" style="color:black; margin:10px;" title="Não existe atuação cadastrada"> <%= new_button_title %></span>
          <% end %>
        </div>
          <div class="box-body table-responsive">
              <table id="example1" class="table table-bordered table-striped table-hover">
                  <thead>
                      <tr>
                        <% cols.each do |col| %>
                            <th><%= col %></th>
                          <% end %>
                      </tr>
                  </thead>
                  <tbody>
                    <% iterator.each do |d| %>
                      <tr>
                          <td><%= d.name %></td>
                          <td><%= d.skill.name %></td>
                          <td width="150"> 
                            <div class="btn-group">
                                <button type="button" class="btn btn-default">Opções</button>
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                  <span class="caret"></span>
                                  <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="/<%= path %>/<%= d.id %>/edit"><i class="fa fa-pencil"></i> Editar</a></li>
                                    <li><a href="/<%= path %>/<%= d.id %>"><i class="fa fa-search"></i> Detalhes</a></li>
                                    <li><a href="/<%= path %>/<%= d.id %>" data-confirm="<%= remove_title %>" data-method="delete" rel="nofollow"><i class="fa fa-trash-o"></i> Remover</a></li>
                                </ul>
                            </div>
                          </td>
                        </tr>
                      <% end %>
                  </tbody>
              </table>
                <br>
                <br>
                <br>
          </div>
      </div>
  </div>
  <br>
</div>
<script type="text/javascript">
    $(function() {
        $('#example1').dataTable({
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
</script>

app/views/skill_contents/new.html.erb
<%= render 'form' %>

app/views/skill_contents/show.html.erb
<% path = "/skill_contents" %>
<% iterator = @skill_content %>

<p id="notice"><%= notice_helper %></p>
<div class="row">
    <div class="col-md-4">
        <div class="box box-primary">
            <div class="box-header">
                  <h3 class="box-title">Dados do Conteúdo da Habilidade</h3>
            </div>
            <div class="box-body">
                <div class="form-group">
                    <label for="">Nome</label>
                    <%= iterator.name %>
                </div>
                <div class="form-group">
                    <label for="">Habilidade</label>
                    <%= iterator.skill.name %>
                </div>
              </div>
              <div class="box-footer">
                <%= link_to 'Novo', new_skill_content_path,:class => "btn btn-primary" %> |
                 <%= link_to 'Editar', edit_skill_content_path(iterator),:class => "btn btn-primary" %> |
                  <%= link_to "Todos conteúdos", path,:class => "btn btn-primary" %> 
              </div>
        </div>
    </div>
</div>