config/routes.rb
Mobile2youServer::Application.routes.draw do

  resources :user_applicants
  resources :status_user_jobs
  resources :mannequin_sizes
  resources :answers
  resources :phones
  resources :questions
  resources :statuses
  resources :nationalities
  resources :origin_countries
  resources :schoolings
  resources :passport_nationalities
  resources :cnhs
  resources :notifications
  resources :portfolios
  resources :addresses
  resources :pictures
  resources :user_apps
  resources :super_admins
  resources :usuarios
  resources :webs
  resources :admins
  resources :skill_contents
  resources :appearance_contents
  resources :performance_contents
  resources :performances
  resources :appearances
  resources :skills
  resources :jobs
  resources :user_producers
  resources :download

  apipie
  devise_for :users
  resources :users

  # match 'pesquisa.agenciamondiale.com.br' => redirect('https://agenciamondiale.com.br/')
  # if request.fullpath.include?("pesquisa.agenciamondiale")
  #    redirect_to "https://agenciamondiale.com.br/"
  #  end

  # get '/' => 'openJob', :constraints => { :subdomain => /.+/ }
  # constraints subdomain: 'pesquisa' do
  #   root to: 'openJob'
  # end

  # constraints subdomain: false do
    # root to: 'webs#open_job'
  # end
  constraints(Subdomain) do
    match '/' => 'webs#open_job'
  end
  root to: 'home#index'

  # get '/webs/download'=> 'webs#download'
  get 'index' => 'webs#index'
  get 'signup' => 'webs#user_signup'
  get 'anunciar' => 'webs#new_job'
  get 'gerenciar' => 'webs#manage_jobs'
  get 'openJob' => 'webs#open_job'
  get 'editOpenJob/:id' => 'webs#edit_open_job'
  get 'openJobSub' => 'webs#open_job_subscribe'
  get 'search' => 'webs#search_users'
  get 'admin' => 'home#index'
  get 'login' => 'home#index'
  get "alterar_senha" => "usuarios#edit"
  get "meu_perfil" => "usuarios#edit"
  get "publicPerfil" => "webs#public_perfil"
  get "editPublicPerfil" => "webs#edit_public_perfil"
  get 'approve/:id' => 'user_apps#approve', as: :approve
  get 'repprove/:id' => 'user_apps#repprove', as: :repprove
  get 'seen/:id' => 'user_applicants#seen', as: :seen
  post 'user_applicants/destroy_many' 
  post 'user_applicants/send_email' 
  get 'get_user_perfil'  => 'webs#get_user_perfil'


  resources :user_applicants, only: [:index, :show] do
    resource :download, only: [:show]
  end

  namespace :web do
    post "users/signin"
    post 'users/new'
    post 'jobs/new'
    post 'jobs/newOpenJob'
    post 'jobs/editOpenJob'
    post 'jobs/apply'
    post 'jobs/applyOpenJob'
    post 'jobs/editApplyOpenJob'
    get 'users/download'  
  end

  namespace :webservices do
    post "login/signin"
    post "login/signinFacebook"
    post "login/signup"
    post "login/forgotPass"
    # get 'jobs/openPesquisaJobs'


    post "account/updatePassword"
    post "account/checkPassword"
    post "account/updatePhoto"
    post "account/registerToken"
    
    # get 'account/getSubscribeInfo'
    # get "account/getAbout"
    # get "account/getNotifications"

    # put "account/updateAbout"
    # put 'account/updateLanguage'

    get "jobs/openJobs"
    get "jobs/myJobs"

    post "jobs/apply"
    post "jobs/addMediaAnswer"

    delete "jobs/removeMediaAnswer"

    get "account/about"
    get "account/myGallery"
    get "account/getCharacteristics"
    get "account/getFirstContact"
    get "account/getSkills"
    get "account/getPersonalData"
    get "account/getSocialNetworks"
    get "account/notifications"
    
    post "account/createFirstContact"
    post "account/addCurriculum"
    post "account/addGallery"
    post "account/addPicture"

    put "account/editFirstContact"
    put "account/editSkills"
    put "account/editPersonalData"
    put "account/editSocialNetworks"
    put "account/editCharacteristics"

    delete "account/removeGallery"
    delete "account/removePicture"
    delete "account/removeCurriculum"
  end

  match ':controller(/:action(/:id))(.:format)'

end

app/models/answer.rb
class Answer
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps
  field :content, type: String

  has_mongoid_attached_file :file,
      :storage        => :s3,
      :bucket_name    => 'Mobile2you',
      :bucket    => 'Mobile2you',
      :styles => {  :small => "130x130>"},
      :path           => ':attachment/:id/:style.:extension',
      :s3_credentials => File.join(Rails.root, 'config', 's3.yml')

  belongs_to :user_app
  belongs_to :user_applicant
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :set_answer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @answers = Answer.all
    respond_with(@answers)
  end

  def show
    respond_with(@answer)
  end

  def new
    @answer = Answer.new
    respond_with(@answer)
  end

  def edit
  end

  def create
    @answer = Answer.new(params[:answer])
    if @answer.save
      if (!params[:video].nil?)      
        @answer.video = Video.new(file: params[:video])
      end
      flash[:notice_success] = 'Resposta criada com sucesso.'
    end
    respond_with(@answer)
  end

  def update
    if (!params[:video].nil?)
      p = @answer.video
      if p.nil?
        @answer.video = Video.new(file: params[:video])
      else
        p.file = params[:video]
        p.save
      end
    end

    flash[:notice_success] = 'Resposta atualizada com sucesso.' if @answer.update_attributes(params[:answer])
    respond_with(@answer)
  end

  def destroy
    @answer.destroy
    respond_with(@answer)
  end

  private
    def set_answer
      @answer = Answer.find(params[:id])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<style type="text/css">
.input-error {
  color :red;
}
</style>
<% iterator = @answer %>
<% title = "Dados da Reposta" %>

<%= form_for(iterator, :validate => true)  do |f| %>
  <div class="row">
    <div class="col-md-8">
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title"><%= title %></h3>
        </div>
        <div class="box-body">
          <!-- nome -->
          <div class="form-group">
              <label for="">Conteudo<span style="color:red">*</span></label>
              <%= f.text_field :content, :placeholder => "Digite o conteudo", :class => "form-control", :required => true %>
          </div>

          <div class="form-group">
            <label for="">Imagem</label>
            <%= f.file_field :picture %>
            <br>
            <a href="<%= iterator.picture.to_s %>" target="blank"> 
                <img src='<%= iterator.picture.to_s %>' width='100px' height='100px' alt='<%= iterator.picture.path %>'>
            </a>
          </div>

          <div class="form-group">
            <label for="">Vídeo</label>
            <%= file_field_tag "video", type: :file, multiple: false %>
            <br>
            <% if !iterator.video.nil? %>
              <% if iterator.file.url == "/files/original/missing.png" %>
                  Sem vídeo
              <% else %>
                  <a href="<%= iterator.file.to_s %>" target="blank"> 
                    <video src='<%= iterator.file.to_s %>' width='100px' height='100px' alt='<%= iterator.file.path %>'>
                </a>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="box-footer">
          <%= f.submit "Salvar", :class => "btn btn-primary" %> 
          <%= link_to "Todas respostas", answers_path,:class => "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>  
<% end %>

app/views/answers/edit.html.erb
<%= render 'form' %>

app/views/answers/index.html.erb
<div class="row">

  <%= notice_helper %>
  <% cols = ["Criado em","Pergunta","Usuário","Resposta","Opções"] %>
  <% path = "answers" %>
  <% remove_title = "Deseja remover esta Resposta?" %>
  <% iterator = @answers.desc(:created_at) %>

  <div class="col-xs-12">
      <div class="box">
          <div class="box-body table-responsive">
              <table id="example1" class="table table-bordered table-striped table-hover">
                  <thead>
                      <tr>
                        <% cols.each do |col| %>
                            <th><%= col %></th>
                          <% end %>
                      </tr>
                  </thead>
                  <tbody>
                    <% iterator.each do |d| %>
                      <tr>
                          <td><%= d.created_at.nil? ? "" : d.created_at.strftime("%d/%m/%Y %H:%M") %></td>
                          <td><%= d.question.title %></td>
                          <td><%= d.user_app.name %></td>
                          <td>
                            <% if d.question.type == 2 || d.question.type == 3 %> 
                              <% if !d.file.nil? %>
                                <% if d.file.to_s != "/files/original/missing.png" %>
                                  <% if d.question.type == 2 %>
                                    <img src='<%= d.file.to_s %>' width='100px' height='100px'>
                                  <% else %>
                                    <video src='<%= d.file.to_s %>' width='100px' height='100px'>
                                  <% end %>
                                <% else %>
                                  Sem conteúdo
                                <% end %>
                              <% end %>
                            <% else %>
                              <%= d.content %>
                            <% end %>
                          </td>
                          <td width="150"> 
                            <div class="btn-group">
                                <button type="button" class="btn btn-default">Opções</button>
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                  <span class="caret"></span>
                                  <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="/<%= path %>/<%= d.id %>/edit"><i class="fa fa-pencil"></i> Editar</a></li>
                                    <li><a href="/<%= path %>/<%= d.id %>"><i class="fa fa-search"></i> Detalhes</a></li>
                                    <li><a href="/<%= path %>/<%= d.id %>" data-confirm="<%= remove_title %>" data-method="delete" rel="nofollow"><i class="fa fa-trash-o"></i> Remover</a></li>
                                </ul>
                            </div>
                          </td>
                        </tr>
                      <% end %>
                  </tbody>
              </table>
                <br>
                <br>
                <br>
          </div>
      </div>
  </div>
  <br>
</div>
<script type="text/javascript">
    $(function() {
        $('#example1').dataTable({
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bSort": false,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
</script>

app/views/answers/new.html.erb
<%= render 'form' %>

app/views/answers/show.html.erb
<% path = "/answers" %>
<% iterator = @answer %>

<p id="notice"><%= notice_helper %></p>
<div class="row">
    <div class="col-md-8">
        <div class="box box-primary">
            <div class="box-header">
                  <h3 class="box-title">Dados da Resposta</h3>
            </div>
            <div class="box-body">
            	<div class="form-group">
                    <label for="">Pergunta</label>
                    <%= sad iterator.question.blank? ? "" : iterator.question.title %>
                </div>
                <div class="form-group">
                    <label for="">Conteudo</label>
                    <%= iterator.content %>
                </div>
                <div class="form-group">
                    <label for="">Imagem</label>
	              	<% if iterator.picture.to_s == "/pictures/original/missing.png" %>
		                  Sem imagem
	              	<% else %>
	                    <%= iterator.picture.to_s %>
                    <% end %>
                </div>
                <div class="form-group">
                    <label for="">Video</label>
                    <% if !iterator.video.nil? %>
	                    <% if iterator.video.file.url == "/files/original/missing.png" %>
		                  	Sem vídeo
		              	<% else %>
		                    <video src="<%= iterator.video.file.to_s %>" width="200" height="200">
	                    <% end %>
                    <% end %>
                </div>
            </div>
            <div class="box-footer">
                <%= link_to 'Nova', new_answer_path,:class => "btn btn-primary" %> |
                <%= link_to 'Editar', edit_answer_path(iterator),:class => "btn btn-primary" %> |
                <%= link_to "Todas repostas", path,:class => "btn btn-primary" %> 
            </div>
        </div>
    </div>
</div>