config/routes.rb
Mobile2youServer::Application.routes.draw do

  resources :user_applicants
  resources :status_user_jobs
  resources :mannequin_sizes
  resources :answers
  resources :phones
  resources :questions
  resources :statuses
  resources :nationalities
  resources :origin_countries
  resources :schoolings
  resources :passport_nationalities
  resources :cnhs
  resources :notifications
  resources :portfolios
  resources :addresses
  resources :pictures
  resources :user_apps
  resources :super_admins
  resources :usuarios
  resources :webs
  resources :admins
  resources :skill_contents
  resources :appearance_contents
  resources :performance_contents
  resources :performances
  resources :appearances
  resources :skills
  resources :jobs
  resources :user_producers
  resources :download

  apipie
  devise_for :users
  resources :users

  # match 'pesquisa.agenciamondiale.com.br' => redirect('https://agenciamondiale.com.br/')
  # if request.fullpath.include?("pesquisa.agenciamondiale")
  #    redirect_to "https://agenciamondiale.com.br/"
  #  end

  # get '/' => 'openJob', :constraints => { :subdomain => /.+/ }
  # constraints subdomain: 'pesquisa' do
  #   root to: 'openJob'
  # end

  # constraints subdomain: false do
    # root to: 'webs#open_job'
  # end
  constraints(Subdomain) do
    match '/' => 'webs#open_job'
  end
  root to: 'home#index'

  # get '/webs/download'=> 'webs#download'
  get 'index' => 'webs#index'
  get 'signup' => 'webs#user_signup'
  get 'anunciar' => 'webs#new_job'
  get 'gerenciar' => 'webs#manage_jobs'
  get 'openJob' => 'webs#open_job'
  get 'editOpenJob/:id' => 'webs#edit_open_job'
  get 'openJobSub' => 'webs#open_job_subscribe'
  get 'search' => 'webs#search_users'
  get 'admin' => 'home#index'
  get 'login' => 'home#index'
  get "alterar_senha" => "usuarios#edit"
  get "meu_perfil" => "usuarios#edit"
  get "publicPerfil" => "webs#public_perfil"
  get "editPublicPerfil" => "webs#edit_public_perfil"
  get 'approve/:id' => 'user_apps#approve', as: :approve
  get 'repprove/:id' => 'user_apps#repprove', as: :repprove
  get 'seen/:id' => 'user_applicants#seen', as: :seen
  post 'user_applicants/destroy_many' 
  post 'user_applicants/send_email' 
  get 'get_user_perfil'  => 'webs#get_user_perfil'


  resources :user_applicants, only: [:index, :show] do
    resource :download, only: [:show]
  end

  namespace :web do
    post "users/signin"
    post 'users/new'
    post 'jobs/new'
    post 'jobs/newOpenJob'
    post 'jobs/editOpenJob'
    post 'jobs/apply'
    post 'jobs/applyOpenJob'
    post 'jobs/editApplyOpenJob'
    get 'users/download'  
  end

  namespace :webservices do
    post "login/signin"
    post "login/signinFacebook"
    post "login/signup"
    post "login/forgotPass"
    # get 'jobs/openPesquisaJobs'


    post "account/updatePassword"
    post "account/checkPassword"
    post "account/updatePhoto"
    post "account/registerToken"
    
    # get 'account/getSubscribeInfo'
    # get "account/getAbout"
    # get "account/getNotifications"

    # put "account/updateAbout"
    # put 'account/updateLanguage'

    get "jobs/openJobs"
    get "jobs/myJobs"

    post "jobs/apply"
    post "jobs/addMediaAnswer"

    delete "jobs/removeMediaAnswer"

    get "account/about"
    get "account/myGallery"
    get "account/getCharacteristics"
    get "account/getFirstContact"
    get "account/getSkills"
    get "account/getPersonalData"
    get "account/getSocialNetworks"
    get "account/notifications"
    
    post "account/createFirstContact"
    post "account/addCurriculum"
    post "account/addGallery"
    post "account/addPicture"

    put "account/editFirstContact"
    put "account/editSkills"
    put "account/editPersonalData"
    put "account/editSocialNetworks"
    put "account/editCharacteristics"

    delete "account/removeGallery"
    delete "account/removePicture"
    delete "account/removeCurriculum"
  end

  match ':controller(/:action(/:id))(.:format)'

end

app/models/cnh.rb
class Cnh
  include Mongoid::Document
  field :name, type: String

  has_and_belongs_to_many :user_apps
end

app/controllers/cnhs_controller.rb
class CnhsController < ApplicationController
  before_filter :set_cnh, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @cnhs = Cnh.all
    respond_with(@cnhs)
  end

  def show
    respond_with(@cnh)
  end

  def new
    @cnh = Cnh.new
    respond_with(@cnh)
  end

  def edit
  end

  def create
    @cnh = Cnh.new(params[:cnh])
    flash[:notice_success] = 'Categoria da CNH criada com Sucesso.' if @cnh.save
    respond_with(@cnh)
  end

  def update
    flash[:notice_success] = 'Categoria da CNH atualizada com Sucesso.' if @cnh.update_attributes(params[:cnh])
    respond_with(@cnh)
  end

  def destroy
    @cnh.destroy
    respond_with(@cnh)
  end

  private
    def set_cnh
      @cnh = Cnh.find(params[:id])
    end
end

app/helpers/cnhs_helper.rb
module CnhsHelper
end

app/views/cnhs/_form.html.erb
<style type="text/css">
.input-error {
  color :red;
}
</style>
<% iterator = @cnh %>
<% title = "Dados da Categoria do CNH" %>

<%= form_for(iterator, :validate => true)  do |f| %>
  <div class="row">
    <div class="col-md-8">
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title"><%= title %></h3>
        </div>
        <div class="box-body">
          <!-- nome -->
          <div class="form-group">
              <label for="">Categoria CNH<span style="color:red">*</span></label>
              <%= f.text_field :name, :placeholder => "Digite a categoria", :class => "form-control", :required => true %>
          </div>
        </div>
        <div class="box-footer">
          <%= f.submit "Salvar", :class => "btn btn-primary" %> 
          <%= link_to "Todas as categorias CNH", jobs_path,:class => "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>  
<% end %>

app/views/cnhs/edit.html.erb
<%= render 'form' %>

app/views/cnhs/index.html.erb
<div class="row">

  <%= notice_helper %>
  <% cols = ["Nome","Opções"] %>
  <% path = "cnhs" %>
  <% new_button_title = "Nova categoria de CNH" %>
  <% remove_title = "Deseja remover esta Categoria?" %>
  <% iterator = @cnhs %>

  <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
            <a href="<%= path %>/new" class="btn btn-primary pull-right" style="color:white; margin:10px;"> <%= new_button_title %></a>
        </div>
          <div class="box-body table-responsive">
              <table id="example1" class="table table-bordered table-striped table-hover">
                  <thead>
                      <tr>
                        <% cols.each do |col| %>
                            <th><%= col %></th>
                          <% end %>
                      </tr>
                  </thead>
                  <tbody>
                    <% iterator.each do |d| %>
                      <tr>
                          <td><%= d.name %></td>
                          <td width="150"> 
                            <div class="btn-group">
                                <button type="button" class="btn btn-default">Opções</button>
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                  <span class="caret"></span>
                                  <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="/<%= path %>/<%= d.id %>/edit"><i class="fa fa-pencil"></i> Editar</a></li>
                                    <li><a href="/<%= path %>/<%= d.id %>"><i class="fa fa-search"></i> Detalhes</a></li>
                                    <li><a href="/<%= path %>/<%= d.id %>" data-confirm="<%= remove_title %>" data-method="delete" rel="nofollow"><i class="fa fa-trash-o"></i> Remover</a></li>
                                </ul>
                            </div>
                          </td>
                        </tr>
                      <% end %>
                  </tbody>
              </table>
                <br>
                <br>
                <br>
          </div>
      </div>
  </div>
  <br>
</div>
<script type="text/javascript">
    $(function() {
        $('#example1').dataTable({
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "bAutoWidth": true
        });
    });
</script>

app/views/cnhs/new.html.erb
<%= render 'form' %>

app/views/cnhs/show.html.erb
<% path = "/cnhs" %>
<% iterator = @cnh %>

<p id="notice"><%= notice_helper %></p>
<div class="row">
    <div class="col-md-8">
        <div class="box box-primary">
            <div class="box-header">
                  <h3 class="box-title">Dados da Categoria da CNH</h3>
            </div>
            <div class="box-body">
                <div class="form-group">
                    <label for="">Nome</label>
                    <%= iterator.name %>
                </div>
            </div>
            <div class="box-footer">
                <%= link_to 'Nova', new_cnh_path,:class => "btn btn-primary" %> |
                <%= link_to 'Editar', edit_cnh_path(iterator),:class => "btn btn-primary" %> |
                <%= link_to "Todas categorias da CNH", path,:class => "btn btn-primary" %> 
            </div>
        </div>
    </div>
</div>